#!/bin/sh
set -e

# Define default values if not set
PORT=${OFFICIAL_PORT:-8080}
DB_PATH=${DB_PATH:-data/messagerie.db}
CERT_FILE=${CERT_FILE:-server.crt}
KEY_FILE=${KEY_FILE:-server.key}
DB_KEY=${DB_KEY:-}

echo "⚙️  Generating server.conf..."
cat > server.conf <<EOF
# Auto-generated by docker-entrypoint.sh
bind_port=$PORT
db_path=$DB_PATH
cert_file=$CERT_FILE
key_file=$KEY_FILE
db_key=$DB_KEY
EOF

echo "✅ Configuration generated."
echo "🚀 Starting Server on port $PORT..."

# Execute the command passed to the docker container (the server binary)
exec "$@"