#!/bin/bash

CERT_FILE="server.crt"
OUTPUT_FILE="include/server_cert.h"

if [ ! -f "$CERT_FILE" ]; then
    echo "⚠️  Warning: $CERT_FILE not found. Run ./gencert.sh first."
    # Create a dummy file so compilation doesn't crash on first run
    echo "#ifndef SERVER_CERT_H" > $OUTPUT_FILE
    echo "#define SERVER_CERT_H" >> $OUTPUT_FILE
    echo "const char *SERVER_CERT_PEM = \"\";" >> $OUTPUT_FILE
    echo "#endif" >> $OUTPUT_FILE
    exit 0
fi

echo "📦 Embedding $CERT_FILE into $OUTPUT_FILE..."

echo "/* Auto-generated by embed_cert.sh */" > $OUTPUT_FILE
echo "#ifndef SERVER_CERT_H" >> $OUTPUT_FILE
echo "#define SERVER_CERT_H" >> $OUTPUT_FILE
echo "" >> $OUTPUT_FILE
echo "const char *SERVER_CERT_PEM = " >> $OUTPUT_FILE

# Read line by line, escape quotes, and add \n
while IFS= read -r line; do
    echo "\"$line\\n\"" >> $OUTPUT_FILE
done < "$CERT_FILE"

echo ";" >> $OUTPUT_FILE
echo "#endif" >> $OUTPUT_FILE

echo "✅ Done."