#!/usr/bin/env bash
set -Eeuo pipefail

# =========================
# MoT Installer
# - Installs to: ~/.mot
# - Configures: ~/.mot/config.conf
# - Provides command: mot
# =========================

# --- RELEASE CONFIGURATION ---
# These values are replaced automatically during 'setup_release.sh'
# DO NOT EDIT MANUALLY unless you are compiling from source yourself.
OFFICIAL_HOST="__OFFICIAL_HOST__"
OFFICIAL_PORT="__OFFICIAL_PORT__"

APP_DIR="${HOME}/.mot"
# We look for the binary in ./bin/ (standard release structure)
# or fallback to local compilation path if running from source
SOURCE_BIN="bin/client"
if [ ! -f "$SOURCE_BIN" ]; then
    SOURCE_BIN="bin/client_linux_amd64"
fi

TARGET_BIN_NAME="client"
WRAPPER_NAME="mot"

BIN_DIR="${APP_DIR}/bin"
LOG_DIR="${APP_DIR}/log"
CONFIG_FILE="${APP_DIR}/config.conf"
WRAPPER_PATH="${APP_DIR}/${WRAPPER_NAME}"

GREEN="\033[0;32m"
YELLOW="\033[0;33m"
RED="\033[0;31m"
NC="\033[0m"

say()  { echo -e "${GREEN}$*${NC}"; }
info() { echo -e "${YELLOW}$*${NC}"; }
err()  { echo -e "${RED}$*${NC}" >&2; }

# =========================
# Main
# =========================
echo "=== MoT Installer ==="

# 1) Check binary exists
if [[ ! -f "$SOURCE_BIN" ]]; then
  err "❌ Error: Binary '$SOURCE_BIN' not found."
  err "   Are you running this from the release folder?"
  exit 1
fi

# Fallback if placeholders weren't replaced (Development Mode)
if [ "$OFFICIAL_HOST" == "__OFFICIAL_HOST__" ]; then
    info "⚠️  Development mode detected (Placeholders found)."
    OFFICIAL_HOST="127.0.0.1"
    OFFICIAL_PORT="8010"
fi

# 2) Create install dirs
info "1) Creating install directory at ${APP_DIR}..."
mkdir -p "$BIN_DIR" "$LOG_DIR"

# 3) Copy binary
info "2) Copying binary..."
cp -f "$SOURCE_BIN" "${BIN_DIR}/${TARGET_BIN_NAME}"
chmod +x "${BIN_DIR}/${TARGET_BIN_NAME}"

# 4) Generate Configuration (NEW)
info "3) Configuring connection..."
if [ ! -f "$CONFIG_FILE" ]; then
    cat > "$CONFIG_FILE" <<EOF
# MoT Configuration
# Generated by install.sh
server_host=$OFFICIAL_HOST
server_port=$OFFICIAL_PORT
# ca_path= (Empty = use embedded official cert)
EOF
    say "   ✅ Created config for $OFFICIAL_HOST"
else
    info "   ℹ️  Config file already exists (skipping overwrite)"
fi

# 5) Create wrapper script
info "4) Creating wrapper script..."
cat > "$WRAPPER_PATH" <<EOF
#!/usr/bin/env bash
set -Eeuo pipefail
APP_DIR="\$HOME/.mot"
cd "\$APP_DIR"
# Pass all arguments to the binary
exec "./bin/${TARGET_BIN_NAME}" "\$@"
EOF
chmod +x "$WRAPPER_PATH"

# 6) Path Setup
if [[ ":$PATH:" != *":$APP_DIR:"* ]]; then
  info "5) Adding $APP_DIR to PATH..."
  SHELL_RC=""
  case "$SHELL" in
    */zsh) SHELL_RC="$HOME/.zshrc" ;;
    */bash) SHELL_RC="$HOME/.bashrc" ;;
    *) SHELL_RC="$HOME/.profile" ;; 
  esac

  if [ -n "$SHELL_RC" ]; then
    if ! grep -q 'export PATH="$HOME/.mot:$PATH"' "$SHELL_RC"; then
      echo '' >> "$SHELL_RC"
      echo '# MoT CLI' >> "$SHELL_RC"
      echo 'export PATH="$HOME/.mot:$PATH"' >> "$SHELL_RC"
      say "   ✅ Added to $SHELL_RC"
    else
      info "   ℹ️  Already in $SHELL_RC"
    fi
  fi
fi

echo ""
say  " Installation Complete!"
echo "   Run 'source ~/.bashrc' (or your shell config) to update PATH."
echo "   Then type 'mot' to start."
echo ""